name: dbt_test
profile: "dbt-test"

version: '1.0.0'
config-version: 2

model-paths: ["models"]
analysis-paths: []
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_test:  # must match name
    staging:
      +materialized: view
    analytics:
      +materialized: table
