version: 2

models:
  - name: ma_rsi
    description: "20/50-day moving averages plus 14-day RSI"
    columns:
      - name: date
        tests:
          - not_null
      - name: symbol
        tests:
          - not_null
      - name: ma_20
        tests:
          - not_null
      - name: rsi_14
        tests:
          - not_null:
              where: "rsi_14 is not null"
