version: 2

models:
  - name: ma_rsi
    description: "20/50-day moving averages plus 14-day RSI"
    columns:
      - name: date
        tests: [not_null]
      - name: symbol
        tests: [not_null]
      - name: ma_20
        tests: [not_null]
      - name: rsi_14
        tests:
          - not_null:
              where: "rsi_14 is not null"

  - name: rsi_heatmap
    description: "Abstract table for plotting RSI heatmap"
    columns:
      - name: date
        tests: [not_null]
      - name: symbol
        tests: [not_null]
      - name: rsi_14
        tests: [not_null]

  - name: rsi_distribution
    description: "RSI vs price % change for histogram"
    columns:
      - name: symbol
        tests: [not_null]
      - name: rsi_14
        tests: [not_null]
      - name: price_change_pct
        tests: [not_null]

  - name: stock_summary
    description: "Average MA20, MA50, RSI per symbol and coverage window"
    columns:
      - name: symbol
        tests: [not_null, unique]
      - name: avg_rsi
      - name: avg_ma_20
      - name: avg_ma_50
      - name: first_date
      - name: last_date
