version: 2

sources:
  - name: raw
    database: "{{ var('snowflake_database') }}"
    schema: raw
    tables:
      - name: stock_prices

models:
  - name: stg_stock_prices
    description: "Cleaned raw stock_prices with proper types"
    columns:
      - name: date
        tests:
          - not_null
      - name: symbol
        tests:
          - not_null
      - name: volume
        tests:
          - not_null
          - unique
